---
development:
  cloud_name: chullman
  api_key: '739343712712963'
  api_secret: dbULw5pmxm1nHX_EtxJCAJnrycM
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: chullman
  api_key: '739343712712963'
  api_secret: dbULw5pmxm1nHX_EtxJCAJnrycM
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: chullman
  api_key: '739343712712963'
  api_secret: dbULw5pmxm1nHX_EtxJCAJnrycM
  enhance_image_tag: true
  static_image_support: false
